[package]
name = "isousb"
version = "0.1.0"
authors = ["Athanaze <sacha.liechti@arsent.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
users = "0.10.0"